# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/X/Documents/GitHub/RISCVCPU/RISCV/RISCV.srcs/sources_1/ip/prgROM/prgROM.xci
# IP: The module: 'prgROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/X/Documents/GitHub/RISCVCPU/RISCV/RISCV.srcs/sources_1/ip/prgROM/prgROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/X/Documents/GitHub/RISCVCPU/RISCV/RISCV.srcs/sources_1/ip/prgROM/prgROM.xci
# IP: The module: 'prgROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/X/Documents/GitHub/RISCVCPU/RISCV/RISCV.srcs/sources_1/ip/prgROM/prgROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
